# Generated by Django 4.0.4 on 2022-04-15 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('bank_email', models.CharField(default='', max_length=200)),
                ('BIC', models.CharField(max_length=9, unique=True)),
                ('PAN', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Operator', 'Operator'), ('Manager', 'Manager'), ('Company-specialist', 'CompanySpecialist'), ('Administrator', 'Administrator')], default='Client', max_length=30),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveBigIntegerField(default=0)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('block_status', models.BooleanField(default=False)),
                ('frozen', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='banks',
            field=models.ManyToManyField(to='Bank.bank'),
        ),
    ]
