# Generated by Django 4.0.4 on 2022-04-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_bank_user_blocked_user_role_bankaccount_user_banks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('PAN', models.CharField(default='', max_length=9, unique=True)),
                ('address', models.CharField(default='', max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_email',
        ),
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='BIC',
            field=models.CharField(default='', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='PAN',
            field=models.CharField(default='', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
