# Generated by Django 4.0.4 on 2022-04-15 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_company_remove_bank_bank_email_bank_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=13, verbose_name='phone')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bank.bank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='blocked',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('operator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Bank.operator')),
            ],
            options={
                'abstract': False,
            },
            bases=('Bank.operator',),
        ),
    ]
