# Generated by Django 4.0.4 on 2022-04-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_operator_remove_bankaccount_blocked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='block_status',
        ),
    ]
