# Generated by Django 4.0.4 on 2022-04-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_remove_bankaccount_block_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='operator',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
