# Generated by Django 4.0.4 on 2022-04-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_remove_user_role_operator_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=13, verbose_name='phone')),
                ('is_approved', models.BooleanField(default=0)),
            ],
        ),
    ]
