# Generated by Django 4.0.4 on 2022-04-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0008_rename_requests_applications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='USERNAME_FIELD',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='USERNAME_FIELD',
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
