# Generated by Django 4.0.4 on 2022-04-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0009_rename_name_bank_username_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
