# Generated by Django 4.0.4 on 2022-04-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0011_remove_applications_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='username',
            new_name='name',
        ),
    ]
