# Generated by Django 4.0.4 on 2022-04-16 17:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0012_rename_username_applications_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='sum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_amount', models.PositiveSmallIntegerField(default=0)),
                ('bank', models.ManyToManyField(to='Bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(default=0)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('block', models.BooleanField(default=False)),
                ('months', models.PositiveSmallIntegerField(default=0)),
                ('percentage_rate', models.FloatField(default=1.0)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(default=0)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('block', models.BooleanField(default=False)),
                ('payment_day', models.DateField(default=datetime.date(2022, 4, 16))),
                ('percentage_rate', models.FloatField(default=0.0)),
                ('months', models.PositiveSmallIntegerField(choices=[(3, 3), (6, 6), (9, 9), (12, 12), (24, 24), (48, 48)], default=3)),
                ('credit_status', models.CharField(choices=[('denied', 'denied'), ('checking', 'checking'), ('accepted', 'accepted')], default='checking', max_length=200)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
