# Generated by Django 4.0.4 on 2022-04-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0013_alter_bankaccount_sum_month_deposit_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='percentage_rate',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bank.month'),
        ),
    ]
