# Generated by Django 4.0.4 on 2022-04-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0014_remove_deposit_percentage_rate_alter_deposit_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.FloatField(default=1)),
                ('bank', models.ManyToManyField(to='Bank.bank')),
            ],
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.AddField(
            model_name='deposit',
            name='interest_rate',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.PROTECT, to='Bank.interestrate'),
            preserve_default=False,
        ),
    ]
