# Generated by Django 4.0.4 on 2022-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0016_remove_month_bank_month_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='bank',
        ),
        migrations.AddField(
            model_name='month',
            name='bank',
            field=models.ManyToManyField(to='Bank.bank'),
        ),
    ]
