# Generated by Django 4.0.4 on 2022-04-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0017_remove_month_bank_month_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(default=0)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('block', models.BooleanField(default=False)),
                ('installment_status', models.CharField(choices=[('denied', 'denied'), ('checking', 'checking'), ('accepted', 'accepted')], default='checking', max_length=200)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.company')),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bank.month')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(default=0)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('block', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.bank')),
                ('interest_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bank.interestrate')),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bank.month')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
