# Generated by Django 4.0.4 on 2022-04-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0018_installment_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Manager', 'Manager'), ('Administrator', 'Administrator')], default='Client', max_length=30),
        ),
    ]
