# Generated by Django 4.0.4 on 2022-04-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0020_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sum',
            new_name='sending_sum',
        ),
    ]
