# Generated by Django 4.0.4 on 2022-04-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0022_credit_approve_deposit_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('denied', 'denied'), ('checking', 'checking'), ('accessed', 'accessed')], default='Manager', max_length=30),
        ),
    ]
