# Generated by Django 4.0.4 on 2022-04-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0023_user_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('denied', 'denied'), ('checking', 'checking'), ('accessed', 'accessed')], default='checking', max_length=30),
        ),
    ]
